import type { Metadata } from "next";
import "../globals.css";
import SmoothScrollWrapper from "../SmoothScrollWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;

  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <body className="antialiased">
        <SmoothScrollWrapper lang={lang}>{children}</SmoothScrollWrapper>
      </body>
    </html>
  );
}
