
export interface BlogPost {
  slug: string;
  title: string;
  content: string;
  author: string;
  date: string;
  image: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'AMBITIOUS-SPACE-PROJECTS-OF-VSSC',
    title: 'C.P.AGENCIES ARE DELIGHTED TO ANNOUNCE THAT WE WILL BE PART OF THE AMBITIOUS SPACE PROJECTS OF VSSC ,INDIA',
    content: 'WE AT C.P.AGENCIES ARE DELIGHTED TO ANNOUNCE THAT WE WILL BE PART OF THE AMBITIOUS SPACE PROJECTS OF VSSC, INDIA THROUGH SUPPLY OF WORLD RENOUNED FACCIN S.P.A, ITALY MAKE CNC ROLLING MACHINE MODEL 4HEP X2084 IS SUPPLIED TO INDIAN SPACE INDUSTRY FOR ROLLING OF THEIR ALUMINUM ALLOY ISO-GRID/WAFFLE PANNELS COMPONENTS. THE PHOTO ATTACHED IS WITH OUR SR.SERVICE ENGINEERS MR.V SATHISH KUMAR FROM OUR CHENNAI OFFICE AND MR.K VIJAYAN FROM OUR BANGALORE OFFICE BEING PRESENT AT PRE-DESPATCH INSPECTION OF THE MACHINE AT FACCIN S.P.A. ITALY.',
    author: 'John Doe',
    date: '17-08-2025',
    image: '/blog1.jpg',
  },
  {
    slug: 'SPACE-PROJECTS-OF-VSSC',
    title: 'C.P.AGENCIES ARE DELIGHTED TO ANNOUNCE THAT WE WILL BE PART OF THE AMBITIOUS SPACE PROJECTS OF VSSC ,INDIA',
    content: 'WE AT C.P.AGENCIES ARE DELIGHTED TO ANNOUNCE THAT WE WILL BE PART OF THE AMBITIOUS SPACE PROJECTS OF VSSC, INDIA THROUGH SUPPLY OF WORLD RENOUNED FACCIN S.P.A, ITALY MAKE CNC ROLLING MACHINE MODEL 4HEP X2084 IS SUPPLIED TO INDIAN SPACE INDUSTRY FOR ROLLING OF THEIR ALUMINUM ALLOY ISO-GRID/WAFFLE PANNELS COMPONENTS. THE PHOTO ATTACHED IS WITH OUR SR.SERVICE ENGINEERS MR.V SATHISH KUMAR FROM OUR CHENNAI OFFICE AND MR.K VIJAYAN FROM OUR BANGALORE OFFICE BEING PRESENT AT PRE-DESPATCH INSPECTION OF THE MACHINE AT FACCIN S.P.A. ITALY.',
    author: 'John Doe',
    date: '17-08-2025',
    image: '/blog1.jpg',
  },
];
